services:

  backend:
    build:
      context: ./studex-backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes: []

  frontend:
    build:
      context: ./studex-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL:          ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    volumes: []
