FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY prisma.config.ts ./
RUN npm install
RUN npx prisma generate

EXPOSE 3001

# src/ di-mount sebagai volume dari docker-compose — hot reload via nodemon
CMD ["npm", "run", "dev"]
